python ./code/main.py -ds baby \
               -l "200" \
               -ep 100 \
               -ncl 3 \
               -dr 0.5 \
               -ldr_reg 0.4 \
               -ldr_text 0.2 \
               -std 0.075 \
               -tstd 0.075 \
               -rtast 20000 \
               -ttast 20000 \
               -es 20 \
               -rs 6 \
               -gpu 0